---
abstract: 'Catalyst::Action::Wizard -- Catalyst module for building wizards'
author:
  - unknown
build_requires:
  Catalyst::Plugin::Session::State::Cookie: 0
  Class::C3: 0
  HTTP::Message: 5.812
  Test::More: 0
  Test::WWW::Mechanize::Catalyst: 0
  ok: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Action-Wizard
provides:
  Catalyst::Action::Wizard:
    file: lib/Catalyst/Action/Wizard.pm
    version: 0.008
  Catalyst::Wizard:
    file: lib/Catalyst/Wizard.pm
    version: 0
  CatalystX::Wizarded:
    file: lib/CatalystX/Wizarded.pm
    version: 0
requires:
  Catalyst: 0.57
  Catalyst::Plugin::Session: 0.19
  Class::C3: 0
  HTTP::Message: 1.57
  perl: 5.006
resources:
  license: http://dev.perl.org/licenses/
version: 0.008
